extends:
  - "eslint:recommended"
  - "prettier"

plugins:
  - "prettier"

parser: "@typescript-eslint/parser"

parserOptions:
  ecmaVersion: 6
  sourceType: module
  ecmaFeatures:
    modules: true

env:
  es6: true
  node: true

settings:
  import/resolver:
    node:
      paths: [src]
      extensions: [.js, .jsx, .ts, .tsx]

rules:
  class-methods-use-this: 0
  consistent-return: 0
  max-classes-per-file: 0
  no-console: 0
  no-empty-function: 0
  no-shadow: 0
  no-underscore-dangle: 0
  no-use-before-define: 0
  no-useless-constructor: 0
  prefer-template: 0
  prettier/prettier: error
  space-in-brackets: 0
